import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Image from "next/image";

const inter = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col md:flex-row h-screen bg-gray-100 ">
          <div className="flex justify-center items-center w-full md:w-1/2  p-4 sm:p-8">
            {children}
          </div>
          <div className="hidden md:block w-1/2">
            <div className="relative w-full h-full">
              <Image
                src="/images/login-image.png"
                alt="Login Image"
                className="object-cover"
                layout="fill"
              />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
