import type { Metadata } from "next";
import  {Poppins} from "next/font/google";
import "./globals.css";

import { Navbar } from "@/components/layout/navbar";

const inter = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={inter.className}
      >
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
