import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { PublicFooter } from "@/app/_navigation/PublicFooter";
import { PublicNavbar } from "@/app/_navigation/PublicNavbar";

const inter = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PublicNavbar />
        {children}
        <PublicFooter />
      </body>
    </html>
  );
}
